<a href="https://colab.research.google.com/github/TuanTony5/Pre-AIO-Warm-up-/blob/main/01_Activation_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Sigmoid Function


In [2]:
import numpy as np

def sigmoid(x):
  """
  Convert x: [-inf,inf] --> y: [0,1]
  """
  return 1 / (1+ np.exp(-x))

x = np.array([1,5,-4,3,-2])
sigmoid(x)

array([0.73105858, 0.99330715, 0.01798621, 0.95257413, 0.11920292])

# 2. Tanh function

In [3]:
def tanh(x):
  """
  Convert x: [-inf,inf] --> y: [-1,1]
  """
  return (2 / (1+ np.exp(-2*x)) ) - 1

x = np.array([1,5,-4,3,-2])
tanh(x)

array([ 0.76159416,  0.9999092 , -0.9993293 ,  0.99505475, -0.96402758])

# 3. Softplus Function


In [4]:
def softplus(x):
  """
  Convert x: [-inf,inf] --> y: (0,inf)
  """
  return np.log(1+np.exp(x))
softplus(x)

array([1.31326169, 5.00671535, 0.01814993, 3.04858735, 0.12692801])

In [5]:
x = np.array([ 1,  5, -4,  3, -2])

# 4. ReLU function:

In [9]:
def relu(x):
  return max(0,x)

x_i = []

for i in range(len(x)):
  x_i.append(relu(x[i]))
x_i


[1, 5, 0, 3, 0]